version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pwd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      etl-network:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    image: etl
    container_name: etl
    networks:
      etl-network:
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_COLLECTION=promozioni
      - MONGO_USERNAME=mongo_user
      - MONGO_PASSWORD=mongo_pwd
      - MONGO_DB_NAME=bmv
    depends_on:
      - mongodb
networks:
  etl-network:
    driver: bridge
volumes:
  mongodb_data:
