select idiniziativa as iniziativa_id,
       codiceiniziativa as codice_iniziativa,
       statoiniziativa as stato_iniziativa,
       nomeiniziativa as nome_iniziativa,
       datainizio as data_inizio,
       datafine as data_fine,
       descrizione as descrizione,
       descrizionedettaglio as dettaglio_descrizione,
       tipologia,
       tipologiautenza as tipologia_utenza,
       canaleassegnazione as canali_assegnazione,
       canaleattivazione as canali_attivazione,
       maxassegnazioni as max_assegnazioni,
       maxattivazioni as max_attivazioni,
       msgassegnazione as msg_assegnazioni,
       nomecampagnasec as nome_campagna_sec,
       flagutilizzatore as flag_utilizzatore,
       codicepartner as codice_partner,
       oadc,
       codiceiniziativaabb as codice_iniziativa_abb,
       codiceoffertaabb as codice_offerta_abb,
       codiceoffertapp as codice_offerta_pp,
       flagwhitelist as flag_white_list,
       flagutentecoop as flag_utente_coop,
       flagportaunamico as flag_porta_un_amico,
       tipologiautilizzatore as tipologia_utilizzatore,
       idwhitelist as white_list_id,
       codiceiniziativagen as codice_iniziativa_gen,
       codicepartnerpin as codice_partner_pin,
       esclusioneassegnamentomb as esclusione_assegnamento_mb,
       esclusioneassegnamentosb as esclusione_assegnamento_sb,
       assegnamentosb as assegnamento_sb,
       esclusioneattivazionemb as esclusione_attivazione_mb,
       esclusioneattivazionesb as esclusione_attivazione_sb,
       attivazionesb as attivazione_sb,
       esclusioneassegnamentoext as esclusione_assegnamento_ext,
       esclusioneattivazioneext as esclusione_attivazione_ext,
       notificadacia as flag_notifica_da_cia,
       maxbruciaturepin as max_bruciature_pin,
       data_inizio_assegnazione as data_inizio_assegnazione,
       data_fine_assegnazione as data_fine_assegnazione,
       data_inizio_attivazione as data_inizio_attivazione,
       data_fine_attivazione as data_fine_attivazione,
       tipo_iniziativa as tipo_iniziativa,
       tipo_promotore as tipo_promotore
from PV_INIZIATIVA
where STATOINIZIATIVA = 'Attiva'