select idbonus as bonus_id,
       iderogatore as erogatore_id,
       idpromozione as promozione_id,
       nomebonus as nome_bonus,
       descrizione,
       codicebonus as codice_bonus,
       codicetub as codice_tub,
       codicetusp as codice_tusp,
       statobonus as stato_bonus,
       quantita,
       categoria,
       sottocategoria1,
       sottocategoria2,
       sottocategoria3,
       tipobonus as tipo_bonus,
       tipoofferta as tipo_offerta,
       serviceprovider as service_provider,
       opzioni,
       canale,
       nomebonuscomm as nome_bonus_comm,
       campagna,
       durata,
       tipooperazione as tipo_operazione,
       motivo,
       cia_idlista as id_lista,
       cia_desclista as descrizione_lista_cia,
       pepc_titolo,
       pepc_categoria,
       pepc_prodotto,
       tipologiavincitore as tipologia_vincitore,
       idwhitelist as white_list_id,
       priorita,
       identity,
       nomecommercialeweb as nome_commerciale_web,
       nomeoffertaproveca as nome_offerta_pro_ve_ca,
       costoabb as costo_abb,
       costomassmarketabb as costo_mass_market_abb,
       costomassmarket as costo_mass_market,
       credminmassmarket as cred_min_mass_market,
       offertaprenotabile as offerta_prenotabile,
       bonusconvergente as bonus_convergente,
       modalitadipagamento as modalita_di_pagamento,
       web_tipologia,
       web_datascadenza as web_data_scadenza,
       web_intervallo,
       web_smsfree as web_sms_free,
       web_nome,
       web_fineofferta as web_fine_offerta,
       nomeoffertasec as nome_offerta_sec,
       nomecampagnasec as nome_campagna_sec,
       inviomtcortesia as invio_mt_cortesia,
       md_idoperazione as md_id_operazione,
       md_tipologiamsisdn as md_tipologia_msisdn,
       md_causaleannullamento as md_causale_annullamento,
       md_inviosms as md_flag_invio_sms,
       md_nomecampagnasec as md_nome_cmpagna_sec,
       md_testomessaggio as md_testo_messaggio,
       md_codiceofferta as md_codice_offerta,
       md_infocoppia as md_info_coppia,
       riduzionedelay as riduzione_delay,
       attivazionecondata as attivazione_con_data,
       offertainscadenza as offerta_in_scadenza,
       idblacklist as black_list_id,
       md_ppmcodiceoffertapp as md_codice_offerta_app,
       md_ppmcodiceoffertaabb as md_codice_offerta_abb,
       sc_cess_codiceoffertapp as sc_cess_codice_offerta_pp,
       sc_cess_disattivazionepp as sc_cess_disattivazione_pp,
       sc_cess_codiceoffertaabb as sc_cess_codice_offerta_abb,
       att_gest_errore as att_gestione_errore,
       att_codice_offerta_pp as att_codice_offerta_pp,
       att_rimborso_pp as att_rimborso_pp,
       att_causale_balance_pp as att_causale_balance_pp,
       att_codice_bonus_pp as att_codice_bonus_pp,
       att_costo_pp as att_costo_pp,
       att_codice_offerta_abb as att_codice_offerta_abb,
       att_rimborso_abb as att_rimborso_abb,
       att_costo_abb as att_costo_abb,
       att_causale_balance_abb as att_causale_balance_abb,
       estensione,
       tipologia_invio as sms_tipo_invio,
       testo_sms as sms_testo_sms,
       la_mittente as sms_mittente
FROM PV_BONUS