SELECT distinct PV_PROMOZIONE.IDPROMOZIONE         AS promozione_id,
       PV_PROMOZIONE.IDEVALUATOR          as evaluetor_id,
       PV_PROMOZIONE.NOMEPROMOZIONE       as nome_promozione,
       PV_PROMOZIONE.DESCRIZIONE          as descrizione,
       PV_PROMOZIONE.DATAINIZIO           as data_inizio_promozione,
       PV_PROMOZIONE.DATAFINE             as data_fine_promozione,
       PV_PROMOZIONE.DATAFINEACQUISIZIONE as data_fine_acquisizione,
       PV_PROMOZIONE.STATOPROMOZIONE      as stato_promozione,
       PV_PROMOZIONE.MSGATTIVAZIONE       as msg_attivazione,
       PV_PROMOZIONE.MSGEROGAZIONE        as msg_erogazione,
       PV_PROMOZIONE.MSGSOLLECITO         as msg_sollecito,
       PV_PROMOZIONE.EROGAZIONEMULTIPLA   as erogazione_multipla,
       PV_PROMOZIONE.CODICETUP            as codice_tup,
       PV_PROMOZIONE.NOTE                 as note,
       PV_PROMOZIONE.DATAULTIMAMODIFICA   as data_ultima_modifica,
       PV_PROMOZIONE.AUTOREULTIMAMODIFICA as autore_ultima_modifica,
       PV_PROMOZIONE.TIPOPROMOZIONE       as tipo_promozione,
       PV_PROMOZIONE.NOMECAMPAGNASMS      as nome_campagna_sms,
       PV_PROMOZIONE.NOMECOMMERCIALEWEB   as nome_commerciale,
       PV_PROMOZIONE.DESCRIZIONE2         as descrizione2,
       PV_PROMOZIONE.TIPOLOGIAUTENZA      as tipologia_utenza,
       PV_PROMOZIONE.CANALE               as canale,
       PV_PROMOZIONE.DELAYEROGAZIONE      as delay_erogazione,
       PV_PROMOZIONE.UTILIZZOSEC          as utilizzo_sec,
       PV_PROMOZIONE.OADC                 as oadc,
       PV_PROMOZIONE.FLAGPORTAUNAMICO     as flag_porta_un_amico,
       PV_PROMOZIONE.FLAGFILTROPORTALE    as flag_filtro_portale,
       PV_PROMOZIONE.NOMECOMMERCIALEWEB   as nome_commerciale_web,
       PV_PROMOZIONE.DESCRIZIONEWEB       as descrizione_web,
       PV_PROMOZIONE.TIPOLOGIAPROMOZIONE  as tipologia_promozione,
       PV_PROMOZIONE.SCENARIO             as scenario,
       PV_PROMOZIONE.OPERAZIONEAPAGAMENTO as operazione_pagamento,
       PV_PROMOZIONE.UPSELLING            as upselling,
       PV_PROMOZIONE.FLAGBLACKLIST        as flag_black_list,
       PV_PROMOZIONE.IDBLACKLIST          as id_black_list,
       PV_PROMOZIONE.INTERESSECIA         as interessecia,
       PV_PROMOZIONE.CODICEOFFERTAPP      as codice_offerta_pp,
       PV_PROMOZIONE.CODICEOFFERTAABB     as codice_offerta_abb,
       PV_PROMOZIONE.CODICEOFFERTAPUA     as codice_offerta_pua,
       PV_PROMOZIONE.ESCLUSIONEEXT        as esclusione_ext,
       PV_PROMOZIONE.FLAGCONSENSO         as flag_consenso,
       PV_PROMOZIONE.TIPOCONSENSO         as tipo_consenso,
       PV_PROMOZIONE.BLACKLISTCONSENSO    as blacklist_consenso,
       PV_PROMOZIONE.PRIORITA             as priorita,
       PV_PROMOZIONE.CONTROLLOMULTIDEVICE as controllo_multidevice,
       PV_PROMOZIONE.FLAGESITOKO          as flagEsito_ko,
       PV_PROMOZIONE.BONUSESITOKO         as bonus_esito_ko
FROM PV_PROMOZIONE, PV_CRITERIO
WHERE PV_PROMOZIONE.IDPROMOZIONE = PV_CRITERIO.IDPROMOZIONE
AND PV_PROMOZIONE.DATAFINE > CURRENT_TIMESTAMP
  AND PV_CRITERIO.TIPO<>'LISTA' AND PV_CRITERIO.TIPO<>'Lista' AND PV_CRITERIO.TIPO<>'Dpps' AND PV_CRITERIO.TIPO<>'MSCOnline' AND PV_CRITERIO.TIPO<>'MNP ABB'
  AND PV_CRITERIO.TIPO<>'TimCard' AND PV_CRITERIO.TIPO<>'Pin-Iniziativa' AND PV_CRITERIO.TIPO<>'Pin-Iniziativa' AND PV_CRITERIO.TIPO<>'Adesione'
  AND PV_CRITERIO.TIPO<>'PortaUnAmico' AND PV_CRITERIO.TIPO<>'Buongiorno' AND PV_CRITERIO.TIPO<>'Sellin' AND PV_CRITERIO.TIPO<>'EventiCIA' AND PV_CRITERIO.TIPO<>'BPM'